#OPERADORES

# AND            &
# OR             |
# X-OR          xor
# NOT          not
#Desp IZQ       <<
#Desp DER       >>


a = 5 & 4
print("Resultado del AND:" , a)

b= 4 | 5
print("Resultado del OR:" , b)

c = 5 ^ 6
print("Resultado del X-OR:" , c)

d = ~3
print("Resultado del NOT:" , d)

izq = 3 << 1
print("Resultado del Desp IZQ :" , izq)

der = 3 >> 1
print("Resultado del Desp DER :" , der)
